[package]
name = "f_function"
version = "0.1.0"
authors = ["S.tatsuya <s.tatsuya0123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
